spring:
  config:
    activate:
      on-profile: server
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(YROBiwrWocFI0OGZCEDse+j/iHoWN4eO216IVv3+HaZP0tsMPfXIMkJqWGfyYFuty/rb4f7UDi9B/OByAgeNxGQbRgwcC7nHTi/lhasIXaRfW/ETFNQo4g==)
            client-secret: ENC(7a9NSzNM7KRlnEW5/UmYcKvcDNrbah0tPTV43EzKUZ1xJi1objqQLUANPHdpp6rv)
            scope: profile, email # 기본값이 openid, profile, email이지만 openid를 등록하게 되면 서비스마다(카카오, 네이버) OAuth2Service를 만들어야하기 때문에 profile, email만 scope로 지정
          kakao:
            client-id: ENC(1HIZn2QzKn4nRunWgWlDbmi6D948IfN/0vuLeoPwwc8oJxlsWOfoU7/K3pOUWG4v)   # REST API 키
            client-secret: ENC(w/Ip7Zu91manw2kqhhRPO6St73p2GOaOhtigoc+qT4pNbH+FKvuALyd7cq9nv1Zt)
            redirect-uri: "http://13.209.179.193:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email, gender, age_range  # 동의 항목
            client-name: Kakao
          naver:
            client-id: ENC(FuYscwF2S65D3gZ1dFQP2VNW6gd5ZxGs5yqltpIvHTw=)   # REST API 키
            client-secret: ENC(35dAwGDL/QoXHR0wUz7dxtlrjk6qk8Bq)
            redirect-uri: "http://13.209.179.193:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, gender, age  # 동의 항목
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Wtjg9OW9Vj1sFhFZwAIPLv9fq4WEjizOS7AG+KWPSMKccZK07ikUYe73+uCBRLlXu9k7DctAOn5XGHItKXped7qSwjF2W9VqiPDVmgmMVXbdBM2uqJev/5oWgW9PKUuTdfSba6v26vpcb42WswgdwIqoV8KI7joMB184GQhc43qf3DREB1KSaG6w5p9tc5Oey90wm7MKqQChqGH61gzPYw==)
    username: ENC(xspPILIAzHK+xciWhlmMVQ==)
    password: ENC(sX8vFMX8vHZldLvVu2TFMjKnev0JaZFK)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: ${key}
mail:
  address:
    admin: ENC(JGBa0PpOXdYVZnt2VnvjmfjIiFzJzEsEMUU9EOaxGt0=)
jwt:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 600
  key: ENC(9d9nAF96s1rYf4Aaq9yt/FPLZ2f24RkPpmWouKdl6q/+6/NsYLqtRrNaMjc3PjXhk7Wpt/Wn86Dp4RMLUONneCGFbnacoFoF)
cron:
  cron1: 0 0 0 * * *
cloud:
  aws:
    s3:
      bucket: ENC(Z4UP4dP48yD4mb3Ua4sYDsgLbQOEIjV+2xiR/MSMkgc=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
    challenge:
      server: trace
#  file:
#    name: ~/codestates/log/challenge66.log