insert into category (type) values (1);
insert into category (type) values (2);
insert into users (email, password, username) values ('jpetran0@google.cn', 'Ju9skkz', 'bhellwing0');
insert into users (email, password, username) values ('svanderwalt1@sciencedirect.com', 'SPLcH1AJRR', 'mcrighton1');
insert into users (email, password, username) values ('jbaudacci2@twitpic.com', 'moMZriaon', 'mnormand2');
insert into users (email, password, username) values ('mbarroux3@techcrunch.com', 'dXMNkROjx', 'kdows3');
insert into users (email, password, username) values ('lgiddings4@livejournal.com', 'VsCPPkNQwkJ', 'mkiwitz4');
insert into users (email, password, username) values ('cjosefs5@sciencedirect.com', 'Q3sgrO', 'whitzke5');
insert into users (email, password, username) values ('ostonary6@dion.ne.jp', 'sPq4Wf4V5T', 'cdainty6');
insert into users (email, password, username) values ('sosherrin7@opera.com', '49n8vbfKQOY', 'brusso7');
insert into users (email, password, username) values ('lswayne8@netvibes.com', 'SlnPfOvP9', 'bobray8');
insert into users (email, password, username) values ('vtomsett9@who.int', '7QA5EOUZS', 'clummasana9');
insert into users (email, password, username) values ('gmerana@nytimes.com', 'UZDITTK0W', 'adraysona');
insert into users (email, password, username) values ('sharmeb@printfriendly.com', 'EoiK0p', 'mposenb');
insert into users (email, password, username) values ('dyatesc@scientificamerican.com', 'bFdayu', 'cpitherickc');
insert into users (email, password, username) values ('kturevilled@vinaora.com', 'kFLIJJW0gH', 'lskewisd');
insert into users (email, password, username) values ('lbalmee@nba.com', '1PfbXMz8Sd', 'cholsteine');
insert into users (email, password, username) values ('bhartingtonf@cnet.com', '55zLUBe8Q4', 'qhazlewoodf');
insert into users (email, password, username) values ('fpuffettg@domainmarket.com', '7qjPxUan', 'gblowingg');
insert into users (email, password, username) values ('okincaidh@cyberchimps.com', 'bO5DUc0BAlTn', 'fgustickeh');
insert into users (email, password, username) values ('rgamlyni@squarespace.com', 'IfwR8YDcItJ', 'dclingoei');
insert into users (email, password, username) values ('bduddanj@typepad.com', 'fnFH17pTtv', 'abannellj');
insert into habit (title, sub_title, body, auth_start_time, auth_end_time, category_id, user_id) values ('Al Franken: God Spoke', 'Mr', 'Proin interdum mauris non ligula pellentesque ultrices.', '2022-08-13 14:58:39', '2022-03-25 05:26:46', 1, 1);
insert into habit (title, sub_title, body, auth_start_time, auth_end_time, category_id, user_id) values ('Girls Gone Dead', 'Dr', 'Etiam vel augue.', '2022-07-04 11:42:52', '2022-10-18 08:24:50', 2, 2);
insert into habit (title, sub_title, body, auth_start_time, auth_end_time, category_id, user_id) values ('Gorko!', 'Honorable', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-10-26 18:58:08', '2022-06-02 07:30:31', 2, 3);
insert into challenge (user_id, habit_id, status) values (1, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (2, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (3, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (4, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (5, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (6, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (7, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (8, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (9, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (10, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (11, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (12, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (13, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (14, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (15, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (16, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (17, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (18, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (19, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (20, 1, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (1, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (2, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (3, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (4, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (5, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (6, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (7, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (8, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (9, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (10, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (11, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (12, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (13, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (14, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (15, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (16, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (17, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (18, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (19, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (20, 2, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (1, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (2, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (3, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (4, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (5, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (6, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (7, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (8, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (9, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (10, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (11, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (12, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (13, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (14, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (15, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (16, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (17, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (18, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (19, 3, 'CHALLENGE');
insert into challenge (user_id, habit_id, status) values (20, 3, 'CHALLENGE');
insert into auth (body, challenge_id, created_at) values ('Vivamus vel nulla eget eros elementum pellentesque.', 1, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Aenean lectus.', 2, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Morbi non lectus.', 3, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 4, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Donec semper sapien a libero.', 5, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Praesent id massa id nisl venenatis lacinia.', 6, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Cras pellentesque volutpat dui.', 7, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nullam varius.', 8, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla justo.', 9, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Pellentesque eget nunc.', 10, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('In sagittis dui vel nisl.', 11, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla tellus.', 12, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Etiam justo.', 13, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Fusce consequat.', 14, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 15, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla mollis molestie lorem.', 16, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 17, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Morbi a ipsum.', 18, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 19, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Sed ante.', 20, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 21, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Sed ante.', 22, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Duis mattis egestas metus.', 23, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Vestibulum sed magna at nunc commodo placerat.', 24, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 25, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Duis ac nibh.', 26, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 27, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Pellentesque ultrices mattis odio.', 28, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 29, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Proin risus.', 30, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Praesent blandit lacinia erat.', 31, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Ut tellus.', 32, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('In sagittis dui vel nisl.', 33, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Aliquam sit amet diam in magna bibendum imperdiet.', 34, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Fusce consequat.', 35, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Suspendisse potenti.', 36, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla justo.', 37, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nunc rhoncus dui vel sem.', 38, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Suspendisse potenti.', 39, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 40, '2023-01-15 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('In eleifend quam a odio.', 2, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Cras non velit nec nisi vulputate nonummy.', 3, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Vivamus vel nulla eget eros elementum pellentesque.', 4, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nunc rhoncus dui vel sem.', 5, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 6, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nunc nisl.', 7, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Ut tellus.', 8, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 9, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 10, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Curabitur gravida nisi at nibh.', 11, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Sed vel enim sit amet nunc viverra dapibus.', 12, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla ut erat id mauris vulputate elementum.', 13, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 14, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Etiam justo.', 15, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Etiam justo.', 16, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Proin at turpis a pede posuere nonummy.', 17, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla mollis molestie lorem.', 18, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Curabitur gravida nisi at nibh.', 19, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Duis bibendum.', 20, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 21, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 22, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Morbi ut odio.', 23, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Morbi ut odio.', 24, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 25, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nulla ac enim.', 26, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 27, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 28, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Praesent lectus.', 29, '2023-01-16 00:00:00');
insert into auth (body, challenge_id, created_at) values ('Aenean fermentum.', 30, '2023-01-16 00:00:00');